version: "3"

services:
  appsmith:
    image: index.docker.io/appsmith/appsmith-ce
    ports:
      - "172.17.0.1:1780:80"
      # - "172.17.0.1:1443:443"
    volumes:
      - ./stacks:/appsmith-stacks
    restart: always
